apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: admission-webhook-pod

resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml

images:
- name: admission-webhook-pod
  newName: zeratullich/admission-webhook-pod
  newTag: latest
