apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-pod
  namespace: admission-webhook-pod
  labels:
    app: admission-webhook-pod
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: admission-webhook-pod
